// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("Exercise");

var set1 = /* record */[
  /* weight */100.0,
  /* reps */5
];

var set2 = /* record */[
  /* weight */100.0,
  /* reps */5
];

var set3 = /* record */[
  /* weight */100.0,
  /* reps */7
];

var exercise_001 = /* sets : :: */[
  set1,
  /* :: */[
    set2,
    /* :: */[
      set3,
      /* [] */0
    ]
  ]
];

var exercise = /* record */[
  /* name */"Squats",
  exercise_001
];

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, "");
    });
  return newrecord;
}

exports.component = component;
exports.set1      = set1;
exports.set2      = set2;
exports.set3      = set3;
exports.exercise  = exercise;
exports.make      = make;
/* component Not a pure module */
