// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var Pervasives  = require("bs-platform/lib/js/pervasives.js");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("Set");

function setToString(set) {
  return React.createElement("dl", undefined, React.createElement("dt", undefined, "weight"), React.createElement("dd", undefined, Pervasives.string_of_float(set[/* weight */0])), React.createElement("dt", undefined, "reps"), React.createElement("dd", undefined, Pervasives.string_of_int(set[/* reps */1])));
}

function make(set, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, setToString(set));
    });
  return newrecord;
}

exports.component   = component;
exports.setToString = setToString;
exports.make        = make;
/* component Not a pure module */
