// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe      = require("reason-react/lib/js/src/reactDOMRe.js");
var ReasonReact     = require("reason-react/lib/js/src/reasonReact.js");
var Set$MyReactApp  = require("./set.js");
var Page$MyReactApp = require("./page.js");

var mySet = /* record */[
  /* weight */100.0,
  /* reps */5
];

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Page$MyReactApp.make("somethin", /* array */[])), "index");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Set$MyReactApp.make(mySet, /* array */[])), "set");

exports.mySet = mySet;
/*  Not a pure module */
